# Tun é…ç½®
tun:
  enable: false
  stack: system # gvisor/mixed
  # åœ¨ MacOS/Windows æ— æ³•è‡ªåŠ¨åŠ«æŒå‘å¾€å±€åŸŸç½‘çš„ dns è¯·æ±‚
  # åœ¨ Android å¦‚å¼€å¯ ç§äººdns åˆ™æ— æ³•è‡ªåŠ¨åŠ«æŒ dns è¯·æ±‚
  # âš ï¸ å¦‚æœè¦åŠ«æŒå‘å¾€å±€åŸŸç½‘ã€ç§äººdnsï¼Œéœ€è¦ä¸“é—¨å®šä¹‰æ²¡åƒçš„dnsåœ°å€
  dns-hijack:
    - 0.0.0.0:53 # é»˜è®¤ä¸ºdns://åè®®
  # auto-detect-interface: true # è‡ªåŠ¨è¯†åˆ«å‡ºå£ç½‘å¡
  # mtu: 1500 # æœ€å¤§ä¼ è¾“å•å…ƒ
  # gso: false # å¯ç”¨é€šç”¨åˆ†æ®µå¸è½½ï¼Œä»…æ”¯æŒ Linux
  # gso-max-size: 65536 # é€šç”¨åˆ†æ®µå¸è½½åŒ…çš„æœ€å¤§å¤§å°
  
  # å¼€å¯åé»˜è®¤ä¼šæ’é™¤æœ¬æœºé»˜è®¤ç½‘æ®µä¸‹çš„IPè¯·æ±‚ï¼ˆğŸ¤”ä¼šæ”¾åœ¨route-exclude-addressä¸­ï¼‰ï¼Œå…¶ä½™çš„IPéƒ½ä¼šè¿›å…¥clashåˆ†æµ
  # ğŸŒ° å‡è®¾åœ¨192.168.88.0/24ç½‘æ®µä¸‹ï¼Œè®¿é—®192.168.1.1ä¼šè¿›å…¥clashåˆ†æµï¼Œ192.168.88.123åˆ™ä¸ä¼šè¿›å…¥clash
  auto-route: true # é…ç½®è·¯ç”±è¡¨ï¼ˆæ”¯æŒmacosã€linuxå³iproute2ã€windowsï¼‰
  # ä½œä¸ºç½‘å…³æ—¶éœ€è¦å¼€å¯ï¼Œè‡ªåŠ¨é…ç½®è¿›å…¥çš„æµé‡æµå‘mihomo clashã€‚ä»…æ”¯æŒ Linux iptablesã€‚âš ï¸ ä¸æ”¯æŒwindowsã€macos
  # æœ¬åœ°æµé‡ä¸ºOUTPUTæµé‡ï¼ˆmihono clashå¯ä»¥å¼€å¯tun.auto-routeå®Œæˆé€æ˜ä»£ç†ï¼‰
  # ç½‘å…³æµé‡ä¸ºFORWARDæµé‡ï¼ˆmihono clashéœ€è¦å¼€å¯tun.auto-redirectå®Œæˆç½‘å…³ä¸‹çš„é€æ˜ä»£ç†ï¼‰
  # âš ï¸ auto-redirectä¼šä¿æŒauto-routeä¸€è‡´çš„è·¯ç”±è¡¨ï¼Œæ‰€ä»¥åªéœ€è¦æ’é™¤auto-route ipç½‘æ®µå³å¯
  # âš ï¸ androidä»…è½¬å‘ipv4æµé‡
  auto-redirect: false
  # å°†æ‰€æœ‰è¿æ¥è·¯ç”±åˆ° tun æ¥é˜²æ­¢æ³„æ¼ï¼Œä½†ä½ çš„è®¾å¤‡å°†æ— æ³•å…¶ä»–è®¾å¤‡è¢«è®¿é—®
  # ğŸ¤” åŸç†ï¼šauto-routeæ˜¯è®¾ç½®çš„iproute2ï¼Œå¼€å¯strict-routeè¿˜ä¼šåœ¨iptablesä¸Šè®¾ç½®ï¼Œå¯ä»¥è§£å†³ç»å¤§éƒ¨åˆ†æµé‡é€ƒé€¸é—®é¢˜
  strict-route: false
  route-address-set: # å°†æŒ‡å®šè§„åˆ™é›†ä¸­çš„ç›®æ ‡ IP CIDR è§„åˆ™æ·»åŠ åˆ°é˜²ç«å¢™, ä¸åŒ¹é…çš„æµé‡å°†ç»•è¿‡è·¯ç”±, ä»…æ”¯æŒ Linuxï¼Œä¸”éœ€è¦ nftablesï¼Œ`auto-route` å’Œ `auto-redirect` å·²å¯ç”¨ã€‚
    - ruleset-1
    - ruleset-2
  route-exclude-address-set: # å°†æŒ‡å®šè§„åˆ™é›†ä¸­çš„ç›®æ ‡ IP CIDR è§„åˆ™æ·»åŠ åˆ°é˜²ç«å¢™, åŒ¹é…çš„æµé‡å°†ç»•è¿‡è·¯ç”±, ä»…æ”¯æŒ Linuxï¼Œä¸”éœ€è¦ nftablesï¼Œ`auto-route` å’Œ `auto-redirect` å·²å¯ç”¨ã€‚
    - ruleset-3
    - ruleset-4
  # éœ€è¦æ’é™¤çš„å±€åŸŸç½‘ç½‘æ®µä¸IP
  route-exclude-address:
    - 192.168.0.0/16
  # éœ€è¦åŒ…æ‹¬çš„å±€åŸŸç½‘ç½‘æ®µä¸IP
  route-address:
    - 0.0.0.0/1
    - 128.0.0.0/1
    - "::/1"
    - "8000::/1"
  # inet4-route-address: # å¯ç”¨ auto-route æ—¶ä½¿ç”¨è‡ªå®šä¹‰è·¯ç”±è€Œä¸æ˜¯é»˜è®¤è·¯ç”±ï¼ˆæ—§å†™æ³•ï¼‰
  #   - 0.0.0.0/1
  #   - 128.0.0.0/1
  # inet6-route-address: # å¯ç”¨ auto-route æ—¶ä½¿ç”¨è‡ªå®šä¹‰è·¯ç”±è€Œä¸æ˜¯é»˜è®¤è·¯ç”±ï¼ˆæ—§å†™æ³•ï¼‰
  #   - "::/1"
  #   - "8000::/1"
  # endpoint-independent-nat: false # å¯ç”¨ç‹¬ç«‹äºç«¯ç‚¹çš„ NAT
  # include-interface: # é™åˆ¶è¢«è·¯ç”±çš„æ¥å£ã€‚é»˜è®¤ä¸é™åˆ¶ï¼Œä¸ `exclude-interface` å†²çª
  #   - "lan0"
  # exclude-interface: # æ’é™¤è·¯ç”±çš„æ¥å£ï¼Œä¸ `include-interface` å†²çª
  #   - "lan1"
  # include-uid: # UID è§„åˆ™ä»…åœ¨ Linux ä¸‹è¢«æ”¯æŒï¼Œå¹¶ä¸”éœ€è¦ auto-route
  # - 0
  # include-uid-range: # é™åˆ¶è¢«è·¯ç”±çš„çš„ç”¨æˆ·èŒƒå›´
  # - 1000:9999
  # exclude-uid: # æ’é™¤è·¯ç”±çš„çš„ç”¨æˆ·
  #- 1000
  # exclude-uid-range: # æ’é™¤è·¯ç”±çš„çš„ç”¨æˆ·èŒƒå›´
  # - 1000:9999

  # Android ç”¨æˆ·å’Œåº”ç”¨è§„åˆ™ä»…åœ¨ Android ä¸‹è¢«æ”¯æŒ
  # å¹¶ä¸”éœ€è¦ auto-route

  # include-android-user: # é™åˆ¶è¢«è·¯ç”±çš„ Android ç”¨æˆ·
  # - 0
  # - 10
  # include-package: # é™åˆ¶è¢«è·¯ç”±çš„ Android åº”ç”¨åŒ…å
  # - com.android.chrome
  # exclude-package: # æ’é™¤è¢«è·¯ç”±çš„ Android åº”ç”¨åŒ…å
  # - com.android.captiveportallogin